# Generated by Django 3.2.7 on 2021-09-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmdl',
            old_name='message',
            new_name='Message',
        ),
        migrations.AlterField(
            model_name='dmdl',
            name='phoneno',
            field=models.CharField(max_length=15),
        ),
    ]
